/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  applecalendar: import("./applecalendar/api"),
  caldavcalendar: import("./caldavcalendar/api"),
  googlecalendar: import("./googlecalendar/api"),
  googlevideo: import("./googlevideo/api"),
  "ics-feedcalendar": import("./ics-feedcalendar/api"),
  stripepayment: import("./stripepayment/api"),
};
