/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { metadata as applecalendar__metadata_ts } from "./applecalendar/_metadata";
import { metadata as caldavcalendar__metadata_ts } from "./caldavcalendar/_metadata";
import { metadata as dailyvideo__metadata_ts } from "./dailyvideo/_metadata";
import { metadata as googlecalendar__metadata_ts } from "./googlecalendar/_metadata";
import { metadata as googlevideo__metadata_ts } from "./googlevideo/_metadata";
import ics_feedcalendar_config_json from "./ics-feedcalendar/config.json";
import { metadata as stripepayment__metadata_ts } from "./stripepayment/_metadata";
export const appStoreMetadata = {
  applecalendar: applecalendar__metadata_ts,
  caldavcalendar: caldavcalendar__metadata_ts,
  dailyvideo: dailyvideo__metadata_ts,
  googlecalendar: googlecalendar__metadata_ts,
  googlevideo: googlevideo__metadata_ts,
  "ics-feedcalendar": ics_feedcalendar_config_json,
  stripepayment: stripepayment__metadata_ts,
};
