/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import dynamic from "next/dynamic";
export const InstallAppButtonMap = {};
export const AppSettingsComponentsMap = {};
export const EventTypeAddonMap = {
  stripepayment: dynamic(() => import("./stripepayment/components/EventTypeAppCardInterface")),
};
export const EventTypeSettingsMap = {
  stripepayment: dynamic(() => import("./stripepayment/components/EventTypeAppSettingsInterface")),
};
